// Image generation manifest for the three CarCleaningNL demos.
// Sizes: landscape_16_9 | square_1_1 | portrait_9_16
export const MANIFEST = [
  // ---------- SHARED documentary before/after ----------
  { id: "ba-ext-before", size: "landscape_16_9", prompt: "Amateur documentary photo taken on a phone: hood and front fender of a dark grey car in daylight, paint looks dull with visible swirl marks, water spots and light scratches, dusty surface, parked on a Dutch driveway with brick paving, overcast soft light, realistic unpolished snapshot look, no text, no words, blank license plate" },
  { id: "ba-ext-after", size: "landscape_16_9", editOf: "ba-ext-before", prompt: "Keep exactly the same car, same camera angle, same framing and same background, but now freshly professionally detailed: deep glossy mirror-like dark grey paint, flawless sharp reflections, zero scratches or water spots, clean bright surface, no text" },
  { id: "ba-int-before", size: "square_1_1", prompt: "Documentary phone photo of a dirty car interior: fabric driver seat with coffee stains and crumbs, dusty dashboard, footwell with sand and dried mud, daylight through the windows, realistic messy family car, no text, no words" },
  { id: "ba-int-after", size: "square_1_1", editOf: "ba-int-before", prompt: "Keep exactly the same car interior, same camera angle and framing, but now professionally deep cleaned: spotless fabric seat with no stains, dust-free dashboard, perfectly clean footwell carpet, fresh and new looking, no text" },
  { id: "ba-seat-split", size: "square_1_1", prompt: "Car fabric seat photographed straight on, the left half visibly dirty with dark stains and grime, the right half perfectly clean and bright after deep extraction cleaning, one sharp vertical dividing line in the middle of the seat, documentary detailing photo, no text, no words" },

  // ---------- DEMO 1 : PORSELEIN (high-key white studio, silver / chrome) ----------
  { id: "p-hero", size: "landscape_16_9", prompt: "Professional automotive photography: a silver luxury sports car in a bright white photo studio, soft diffused light, glossy paint with elegant reflections on a seamless porcelain-white floor, minimalist, high-end car detailing showcase, lots of negative space above the car, no text, no words, blank license plate" },
  { id: "p-hero-tall", size: "portrait_9_16", prompt: "Professional automotive photography, vertical composition: front three-quarter view of a silver luxury sports car in a bright seamless white photo studio, soft diffused high-key light, glossy reflections on porcelain-white floor, generous empty space at the top, minimalist, no text, blank license plate" },
  { id: "p-wheel", size: "square_1_1", prompt: "Close-up of a freshly polished silver alloy wheel with a glossy brake caliper on a luxury car, bright white photo studio, soft diffused high-key light, subtle chrome reflections, minimalist product photography, no text" },
  { id: "p-interior", size: "square_1_1", prompt: "Pristine cream leather car interior after professional detailing, seen from the open door, bright airy white studio light, soft shadows, luxurious and minimalist, product photography, no text" },
  { id: "p-foam", size: "landscape_16_9", prompt: "A silver luxury car covered in thick white snow foam during a premium hand wash, bright white studio environment, high-key soft lighting, elegant and clean, fine foam texture visible, no text" },
  { id: "p-coating", size: "square_1_1", prompt: "Macro photograph of a black-gloved hand applying ceramic coating with a small square applicator pad on silver car paint, one clean wet line of coating visible, bright clean studio light, shallow depth of field, no text" },
  { id: "p-koplamp", size: "square_1_1", prompt: "Crystal clear restored car headlight in close-up on a silver car, bright white studio, soft elegant reflections in the lens, product photography style, no text" },
  { id: "p-gallery-1", size: "landscape_16_9", prompt: "A pearl white luxury SUV freshly detailed, parked in a bright minimal white studio, deep glossy paint, soft daylight, elegant composition, no text, blank license plate" },
  { id: "p-halen", size: "landscape_16_9", prompt: "A gleaming silver car parked in front of a modern Dutch brick family house, bright fresh morning light, tidy street, professional car pickup and delivery service scene, no people visible, no text, blank license plate" },

  // ---------- DEMO 2 : ACID WERKPLAATS (dark workshop, chartreuse rim light) ----------
  { id: "a-hero", size: "landscape_16_9", prompt: "A black sports car in a dark industrial workshop at night, dramatic chartreuse yellow-green rim lighting outlining the glossy body lines, deep black paint with sharp green highlights, cinematic moody atmosphere, dark concrete floor with subtle reflections, no text, no words, blank license plate" },
  { id: "a-hero-tall", size: "portrait_9_16", prompt: "Vertical cinematic shot: front of a black sports car in a dark industrial workshop, dramatic chartreuse yellow-green rim light tracing the hood and headlights, deep blacks, moody, space at the top of the frame, no text, blank license plate" },
  { id: "a-polish", size: "landscape_16_9", prompt: "A detailer in dark work clothes machine-polishing glossy black car paint with an orbital polisher, dark industrial workshop, dramatic green-tinted work light from one side, cinematic contrast, motion in the polisher pad, no text" },
  { id: "a-wheel", size: "square_1_1", prompt: "Close-up of a matte black alloy wheel with glossy black brake caliper on a black sports car, dark workshop, single chartreuse green accent light from the side, moody cinematic product shot, no text" },
  { id: "a-interior", size: "square_1_1", prompt: "Black alcantara and leather sports car interior being steam cleaned with a steam nozzle, visible steam, dark moody workshop, focused cool task lighting with a green tint, cinematic detail shot, no text" },
  { id: "a-koplamp", size: "square_1_1", prompt: "Car headlight in extreme close-up in a dark workshop: the left half foggy, yellowed and oxidized, the right half crystal clear and freshly restored, dramatic side light with a subtle green tint, cinematic, no text" },
  { id: "a-foam", size: "landscape_16_9", prompt: "A black sports car covered in thick white snow foam at night in a dark workshop wash bay, chartreuse green accent lighting cutting through the scene, high contrast cinematic look, no text" },
  { id: "a-coating", size: "square_1_1", prompt: "Extreme macro of water droplets beading perfectly on jet black ceramic coated car paint, dark background, one sharp chartreuse green light reflection in each droplet, cinematic, no text" },
  { id: "a-halen", size: "landscape_16_9", prompt: "A glossy black car parked in a Dutch residential street at dusk, warm street lights starting to glow, moody blue hour atmosphere, cinematic composition, no people, no text, blank license plate" },

  // ---------- DEMO 3 : TERRACOTTA AVONDLICHT (golden hour, warm film look) ----------
  { id: "t-hero", size: "landscape_16_9", prompt: "A classic 1970s sports car in warm golden hour light, terracotta and amber tones, parked in front of an old Dutch brick warehouse, long warm shadows across cobblestones, vintage automotive poster atmosphere, analog film photography look with soft grain, no text, no words, blank license plate" },
  { id: "t-hero-tall", size: "portrait_9_16", prompt: "Vertical composition: a classic 1970s sports car at golden hour, warm terracotta and amber light, old Dutch brick wall behind, long shadows, analog film look with soft grain, space at the top of the frame, no text, blank license plate" },
  { id: "t-cabrio", size: "square_1_1", prompt: "A convertible car with a dark fabric soft top being gently cleaned with a soft brush, warm golden afternoon light, weathered brick wall background, warm analog film tones, no text" },
  { id: "t-interior", size: "square_1_1", prompt: "Warm cognac tan leather car interior with golden evening sunlight streaming through the window, rich warm tones, dust motes in the light, analog film photography look, no text" },
  { id: "t-polish", size: "landscape_16_9", prompt: "A detailer hand-polishing the fender of a deep oxblood red vintage car at sunset, warm golden light flooding through tall workshop windows, dust particles floating in the light beams, cinematic analog film look, no text" },
  { id: "t-chrome", size: "square_1_1", prompt: "Close-up of freshly polished chrome trim on a vintage car reflecting a warm orange sunset, terracotta tones, shallow depth of field, analog film grain, no text, no badges with text" },
  { id: "t-wash", size: "landscape_16_9", prompt: "Hands washing a classic car with a soft lambswool wash mitt, backlit by low warm golden hour sun, water droplets sparkling in the light, warm film photography look, no text" },
  { id: "t-gallery-1", size: "landscape_16_9", prompt: "A modern glossy burgundy car freshly detailed, parked on a Dutch cobblestone street at golden hour, warm terracotta light, old brick houses softly blurred behind, analog film look, no text, blank license plate" },
  { id: "t-halen", size: "landscape_16_9", prompt: "Car keys being handed from one hand to another in front of a Dutch brick house at golden hour, warm friendly atmosphere, shallow depth of field, warm film tones, no faces visible, no text" },
];
